"""Agregar imagen_url a Producto

Revision ID: 9b2e24a0f259
Revises: a11fd058f4a2
Create Date: 2025-05-26 00:42:29.933646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2e24a0f259'
down_revision = 'a11fd058f4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=250), nullable=True))
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
